<?xml version="1.0" encoding="UTF-8"?>
<definitions name="SupermarketProxyService" targetNamespace="http://proxy.dynamic.baile.usp/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://dynamic.baile.usp/" xmlns:tns="http://proxy.dynamic.baile.usp/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://dynamic.baile.usp/" location="1">
    </import>
  <binding name="SupermarketProxyPortBinding" type="ns1:Supermarket">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="purchase">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
    <operation name="findItem">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="SupermarketProxyService">
    <port name="SupermarketProxyPort" binding="tns:SupermarketProxyPortBinding">
      <soap:address location="http://localhost:1238/marketproxy"/>
    </port>
  </service>
</definitions>
