<?xml version="1.0" encoding="UTF-8"?>
<definitions name="GreetingAddresserService" targetNamespace="http://greeting.baile.usp/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://greeting.baile.usp/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://greeting.baile.usp/" schemaLocation="addresser_xsd_1"/>
    </xsd:schema>
  </types>
  <message name="getEndpoint">
    <part name="parameters" element="tns:getEndpoint">
    </part>
  </message>
  <message name="getEndpointResponse">
    <part name="parameters" element="tns:getEndpointResponse">
    </part>
  </message>
  <portType name="Addresser">
    <operation name="getEndpoint">
      <input message="tns:getEndpoint">
    </input>
      <output message="tns:getEndpointResponse">
    </output>
    </operation>
  </portType>
  <binding name="GreetingAddresserPortBinding" type="tns:Addresser">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="getEndpoint">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="GreetingAddresserService">
    <port name="GreetingAddresserPort" binding="tns:GreetingAddresserPortBinding">
      <soap:address location="http://localhost:1238/addresser"/>
    </port>
  </service>
</definitions>
